In [1]:
import numpy as np
from scipy.signal import convolve2d


In [11]:
# Given Matrix
matrix = np.array([
    [0, 234, 228, 0, 0],
    [0, 234, 228, 0, 0],
    [0, 234, 228, 0, 0],
    [0, 234, 228, 0, 0],
    [0, 234, 228, 0, 0]
],dtype=np.int16)

# Laplacian Kernel
laplacian_kernel = np.array([[0, -1, 0], [-1, 4, -1], [0, -1, 0]],dtype=np.int16)

# Apply Laplacian filter
laplacian_result = convolve2d(matrix, laplacian_kernel, mode='same', boundary='symm')
laplacian_result = np.array(laplacian_result,dtype=np.int16)

# Threshold for edge detection

threshold = 128  # Adjust as needed
edges = np.abs(laplacian_result) > threshold

# Print results
print("Original Matrix:")
print(matrix)
print("\nLaplacian Result:")
print(laplacian_result)
print("\nEdges (Detected Contours):")
print(edges)

Original Matrix:
[[  0 234 228   0   0]
 [  0 234 228   0   0]
 [  0 234 228   0   0]
 [  0 234 228   0   0]
 [  0 234 228   0   0]]

Laplacian Result:
[[-234  240  222 -228    0]
 [-234  240  222 -228    0]
 [-234  240  222 -228    0]
 [-234  240  222 -228    0]
 [-234  240  222 -228    0]]

Edges (Detected Contours):
[[ True  True  True  True False]
 [ True  True  True  True False]
 [ True  True  True  True False]
 [ True  True  True  True False]
 [ True  True  True  True False]]
