In [41]:
import cv2
import numpy as np

# TP10 Color detection

In [42]:

#BLEU
low = np.array([95,80,60])

high = np.array([115,255,150])

# ROSE
low = np.array([120,30,60])

high = np.array([160,110,255])


In [43]:
def detect_inrange(image,low,high,min,max):
    points = []

    image = cv2.blur(image,(5,5))
    image = cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
    mask = cv2.inRange(image,low,high)
    elements = cv2.findContours(mask,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)[-2]
    elements = sorted(elements,key=lambda x:cv2.contourArea(x),reverse=True)

    for elem in elements:
        if cv2.contourArea(elem) < max and min < cv2.contourArea(elem):
            ((x,y),rayon) = cv2.minEnclosingCircle(elem)

            points.append([int(x),int(y),int(rayon),int(cv2.contourArea(elem))])

    return image,mask,points      

In [44]:
cap = cv2.VideoCapture(0)
fw,fh = int(cap.get(3)),int(cap.get(4))
fourcc = cv2.VideoWriter_fourcc("X","V","I","D")
out = cv2.VideoWriter("output.avi",fourcc,2,(fw,fh))


if not cap.isOpened():
    print("erreur")
    exit(0)

while cap.isOpened():
    ret,frame = cap.read()
    if not ret :
        print("erreur cap.reead")

    image,mask,points = detect_inrange(frame,low,high,500,4000)

    image = cv2.cvtColor(image,cv2.COLOR_HSV2BGR)
    cv2.circle(image,(100,100),20,(0,255,0),5)
    
    print(image[100,100])

    if len(points) > 0:
        point = points[0]
        cv2.circle(image,(point[0],point[1]),point[2],(255,0,0),2)
        cv2.putText(image,str(point[3]),(point[0],point[1]),cv2.FONT_HERSHEY_COMPLEX,1,(255,0,0),2,cv2.LINE_AA)

    if mask is not None:
        cv2.imshow("mask",mask)

    
    out.write(image)
    cv2.imshow("cam",image)

    if cv2.waitKey(200) & 0xFF == ord("q"):
        break

out.release()
cap.release()
cv2.destroyAllWindows()

[135 135 132]
[126 137 135]
[127 137 131]
[125 136 130]
[128 135 130]
[128 137 132]
[124 135 135]
[124 137 130]
[123 136 139]
[128 136 132]
[130 133 129]
[133 133 128]
[129 136 132]
[131 135 130]
[135 135 131]
[135 132 130]
[135 136 131]
[134 135 130]
[129 136 129]
[132 135 130]
[131 134 134]
[132 135 133]
[131 135 131]
[134 134 132]
[132 132 130]
[129 135 132]
[132 132 130]
[127 133 129]
[130 134 132]
[127 131 126]
[126 131 127]
[115 123 119]
[119 123 121]
[125 130 122]
[126 130 124]
[84 84 79]
[ 6 19 28]
[0 1 4]
[0 0 5]
[114 111 105]
[132 133 137]
[137 136 131]
[148 145 139]
[154 151 143]
[39 45 41]
[0 0 4]
[ 0  6 12]
[163 156 148]
[190 183 172]
[193 189 180]
[193 190 179]
[191 190 181]
[190 189 175]
[191 189 179]
[191 190 178]
[193 186 180]
[192 188 180]
[192 188 182]
[191 185 179]
[186 183 175]
[184 178 171]
[181 175 168]
[178 173 170]
[175 172 166]
[174 171 163]
[171 166 164]
[168 164 158]
[169 164 161]
[169 165 159]
[166 162 152]
[161 157 145]
[160 156 149]
[160 157 151]
[159 156