In [1]:
import cv2
import numpy as np

# TP10 Color detection

In [17]:

#BLEU
low = np.array([95,80,60])

high = np.array([115,255,150])

# ROSE
low = np.array([120,30,60])

high = np.array([160,110,255])


In [18]:
def detect_inrange(image,low,high,min,max):
    points = []

    image = cv2.blur(image,(5,5))
    image = cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
    mask = cv2.inRange(image,low,high)
    elements = cv2.findContours(mask,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)[-2]
    elements = sorted(elements,key=lambda x:cv2.contourArea(x),reverse=True)

    for elem in elements:
        if cv2.contourArea(elem) < max and min < cv2.contourArea(elem):
            ((x,y),rayon) = cv2.minEnclosingCircle(elem)

            points.append([int(x),int(y),int(rayon),int(cv2.contourArea(elem))])

    return image,mask,points      

In [24]:
cap = cv2.VideoCapture(0)
fw,fh = int(cap.get(3)),int(cap.get(4))
fourcc = cv2.VideoWriter_fourcc("X","V","I","D")
out = cv2.VideoWriter("output.avi",fourcc,2,(fw,fh))


if not cap.isOpened():
    print("erreur")
    exit(0)

while cap.isOpened():
    ret,frame = cap.read()
    if not ret :
        print("erreur cap.reead")

    image,mask,points = detect_inrange(frame,low,high,500,4000)

    image = cv2.cvtColor(image,cv2.COLOR_HSV2BGR)
    cv2.circle(image,(100,100),20,(0,255,0),5)
    conv = cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
    print(cv2.cvtColor(conv,cv2.COLOR_BGR2HSV))

    if len(points) > 0:
        point = points[0]
        cv2.circle(image,(point[0],point[1]),point[2],(255,0,0),2)
        cv2.putText(image,str(point[3]),(point[0],point[1]),cv2.FONT_HERSHEY_COMPLEX,1,(255,0,0),2,cv2.LINE_AA)

    if mask is not None:
        cv2.imshow("mask",mask)

    
    out.write(image)
    cv2.imshow("cam",image)

    if cv2.waitKey(200) & 0xFF == ord("q"):
        break

out.release()
cap.release()
cv2.destroyAllWindows()

[[[169 194 202]
  [168 191 191]
  [167 180 174]
  ...
  [110  87 105]
  [108  80 105]
  [118  66 104]]

 [[169 190 200]
  [168 185 190]
  [167 177 173]
  ...
  [113  73 102]
  [119  67 103]
  [120  57 103]]

 [[170 182 202]
  [169 175 191]
  [168 159 172]
  ...
  [120  74 103]
  [124  76 101]
  [128  78 102]]

 ...

 [[ 55 238 194]
  [ 56 238 210]
  [ 56 239 210]
  ...
  [ 46 237 157]
  [ 45 237 154]
  [ 46 237 156]]

 [[ 55 235 191]
  [ 56 235 206]
  [ 56 239 219]
  ...
  [ 47 235 162]
  [ 46 234 159]
  [ 47 235 167]]

 [[ 56 232 197]
  [ 56 235 219]
  [ 56 238 219]
  ...
  [ 47 233 161]
  [ 48 234 170]
  [ 48 236 172]]]
[[[166 208 197]
  [166 204 186]
  [164 195 171]
  ...
  [130 180 170]
  [130 183 171]
  [129 177 170]]

 [[166 209 198]
  [165 203 187]
  [164 195 171]
  ...
  [130 179 168]
  [130 183 169]
  [129 174 171]]

 [[166 208 197]
  [166 200 185]
  [164 192 170]
  ...
  [130 183 171]
  [130 180 170]
  [131 189 173]]

 ...

 [[ 53 236 203]
  [ 53 236 203]
  [ 53 238 208]
  ..